
USE DATABASE VENTAS_DB;
USE SCHEMA PUBLIC;

DROP TABLE IF EXISTS STG_TEMP_SALES;
DROP TABLE IF EXISTS STG_SALES;
DROP TABLE IF EXISTS TEST_TABLE;

-- Si ya no necesitas el External Stage
-- DROP STAGE IF EXISTS my_s3_stage;

SHOW TABLES;
SHOW STAGES;